### ISSUE TITLE
`/storage/emulated/0/XSSLUnpinning/app.conf: open failed: EACCES (Permission denied)`

### ISSUE THREAD

**Issue by daniula** [ac-pm/SSLUnpinning_Xposed#4]
I've installed Xposed and SSLUnpinning on freshly rooted Android 6 but I can't make it work. I've found this exception in logcat:
```
03-21 12:02:27.420  4009  4009 W System.err: java.io.FileNotFoundException: /storage/emulated/0/XSSLUnpinning/app.conf: open failed: EACCES (Permission denied)
03-21 12:02:27.421  4009  4009 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:452)
03-21 12:02:27.421  4009  4009 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
03-21 12:02:27.421  4009  4009 W System.err: 	at java.io.FileReader.<init>(FileReader.java:42)
03-21 12:02:27.421  4009  4009 W System.err: 	at mobi.acpm.sslunpinning.ConfigUtil.readFromFile(ConfigUtil.java:48)
03-21 12:02:27.421  4009  4009 W System.err: 	at mobi.acpm.sslunpinning.Module.handleLoadPackage(Module.java:34)
03-21 12:02:27.421  4009  4009 W System.err: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
03-21 12:02:27.421  4009  4009 W System.err: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:35)
03-21 12:02:27.421  4009  4009 W System.err: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:71)
03-21 12:02:27.421  4009  4009 W System.err: 	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:176)
03-21 12:02:27.422  4009  4009 W System.err: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:661)
03-21 12:02:27.422  4009  4009 W System.err: 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
03-21 12:02:27.422  4009  4009 W System.err: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
03-21 12:02:27.422  4009  4009 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
03-21 12:02:27.422  4009  4009 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-21 12:02:27.422  4009  4009 W System.err: 	at android.os.Looper.loop(Looper.java:148)
03-21 12:02:27.422  4009  4009 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
03-21 12:02:27.422  4009  4009 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
03-21 12:02:27.422  4009  4009 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-21 12:02:27.422  4009  4009 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-21 12:02:27.422  4009  4009 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
03-21 12:02:27.422  4009  4009 W System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
03-21 12:02:27.422  4009  4009 W System.err: 	at libcore.io.Posix.open(Native Method)
03-21 12:02:27.422  4009  4009 W System.err: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
03-21 12:02:27.422  4009  4009 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:438)
03-21 12:02:27.422  4009  4009 W System.err: 	... 19 more
```

**Comment by ac-pm** [comment]
So far I have not tested on android 6. I will look that. Thanks.

**Comment by ac-pm** [comment]
Ok! Added XPrefs instead of read/write file.
