### ISSUE TITLE
"Class ref in pre-verified class resolved to unexpected implementation" error

### ISSUE THREAD

**Issue by nowind** [ac-pm/SSLUnpinning_Xposed#5]
Loading modules from /data/app/mobi.acpm.sslunpinning-2.apk
  Loading class mobi.acpm.sslunpinning.Module
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:222)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
	at dalvik.system.DexPathList.findClass(DexPathList.java:322)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:421)
	at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
	at dalvik.system.NativeStart.main(Native Method)
on android 4.4.2

**Comment by d4rkuzs** [comment]
I had this same issue too :(

**Comment by ac-pm** [comment]
Done! Set the lib to "provided" instead of "compile".
